spring.application.name=electronicsales
spring.datasource.url=${URL_DB}
spring.datasource.username=${USERNAME_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
jwt.secret=${JWT_SECRET}
key.secret=${SECRET_KEY}
server.port=8090
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_SCOPE}
spring.security.oauth2.client.provider.google.authorization-uri=${GOOGLE_AUTHORIZATION_URI}
spring.security.oauth2.client.provider.google.token-uri=${GOOGLE_TOKEN_URI}
spring.security.oauth2.client.provider.google.user-info-uri=${GOOGLE_USER_INFO_URI}
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}
#spring.redis.host=${HOST_REDIS}
#spring.redis.port=${PORT_REDIS}
spring.data.redis.host=${HOST_REDIS}
spring.data.redis.port=${PORT_REDIS}
spring.data.redis.password=${PASSWORD_REDIS}
spring.mail.host=${HOST_MAIL}
spring.mail.port=${PORT_MAIL}
spring.mail.username=${USERNAME_GOOGLE}
spring.mail.password=${PASSWORD_GOOGLE}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
cloudinary.cloud-name=${CLOUD_NAME}
cloudinary.api-key=${API_KEY}
cloudinary.api-secret=${API_SECRET}
PAYOS_CLIENT_ID=${PAYOS_CLIENT_ID}
PAYOS_API_KEY=${PAYOS_API_KEY}
PAYOS_CHECKSUM_KEY=${PAYOS_CHECKSUM_KEY}
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.address=0.0.0.0


